//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudApp
{
    using System;
    using System.Collections.Generic;

    public class ReservationForTable
    {
        public int Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Total_Table_Number { get; set; }
        public string Total_Person { get; set; }
        public string Booking_Id { get; set; }
    }
}
